// Beispiel-Kleidungsstuecke - ein vollstaendig ausgefuelltes Demo-Teil pro Kategorie,
// inklusive eigener Illustration unter /public/seed. Feste IDs, damit erneutes Laden
// die gleichen 9 Teile aktualisiert statt zu duplizieren.

export const DEMO_ITEMS = [
  {
    id: 'demo-oberteil',
    category: 'oberteil',
    subtype: 'Oversized Pullover',
    image: '/seed/oberteil.svg',
    colorHex: '#8e8e8e', colorLabel: 'Grau', colorFamily: 'grau', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['herbst', 'winter'], material: 'Wolle-Mix',
    brand: 'COS', size: 'M', fit: 'Oversized', price: '69.00',
    notes: 'Sehr weich, gut zum Kombinieren mit Jeans.',
    wornCount: 4, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  },
  {
    id: 'demo-hose',
    category: 'hose',
    subtype: 'Straight Fit Jeans',
    image: '/seed/hose.svg',
    colorHex: '#3b6ea5', colorLabel: 'Blau', colorFamily: 'blau', colorHue: 210, isNeutral: false,
    pattern: 'uni', season: ['fruehling', 'herbst', 'sommer', 'winter'], material: 'Baumwolle-Denim',
    brand: 'Levi\'s', size: '32/32', fit: 'Regular', price: '89.90',
    notes: 'Klassiker, passt zu fast allem.',
    wornCount: 12, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 90,
  },
  {
    id: 'demo-rock',
    category: 'rock',
    subtype: 'Plisseerock Midi',
    image: '/seed/rock.svg',
    colorHex: '#c9a876', colorLabel: 'Beige', colorFamily: 'beige', colorHue: 35, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer'], material: 'Polyester',
    brand: 'Zara', size: 'S', fit: 'Weit', price: '39.95',
    notes: 'Toll fuer den Buero-Look mit Bluse.',
    wornCount: 2, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
  },
  {
    id: 'demo-kleid',
    category: 'kleid',
    subtype: 'Sommerkleid A-Linie',
    image: '/seed/kleid.svg',
    colorHex: '#b3402f', colorLabel: 'Rot', colorFamily: 'rot', colorHue: 10, isNeutral: false,
    pattern: 'uni', season: ['sommer'], material: 'Leinen-Mix',
    brand: 'Mango', size: 'M', fit: 'Tailliert', price: '54.90',
    notes: 'Perfekt fuer heisse Tage, luftig.',
    wornCount: 3, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 45,
  },
  {
    id: 'demo-jacke',
    category: 'jacke',
    subtype: 'Wollmantel Camel',
    image: '/seed/jacke.svg',
    colorHex: '#b08d5b', colorLabel: 'Braun', colorFamily: 'braun', colorHue: 35, isNeutral: true,
    pattern: 'uni', season: ['herbst', 'winter'], material: 'Wolle',
    brand: 'Massimo Dutti', size: 'M', fit: 'Regular', price: '189.00',
    notes: 'Investment-Piece, haelt sehr warm.',
    wornCount: 6, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 60,
  },
  {
    id: 'demo-schuhe',
    category: 'schuhe',
    subtype: 'Leder-Sneaker Weiss',
    image: '/seed/schuhe.svg',
    colorHex: '#f2f2ee', colorLabel: 'Weiss', colorFamily: 'weiss', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer', 'herbst'], material: 'Leder',
    brand: 'Common Projects', size: '42', fit: 'Regular', price: '149.00',
    notes: 'Neutraler Allrounder-Schuh.',
    wornCount: 18, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 120,
  },
  {
    id: 'demo-accessoire',
    category: 'accessoire',
    subtype: 'Seidenschal',
    image: '/seed/accessoire.svg',
    colorHex: '#6b3f5c', colorLabel: 'Lila', colorFamily: 'lila', colorHue: 300, isNeutral: false,
    pattern: 'uni', season: ['herbst', 'winter', 'fruehling'], material: 'Seide',
    brand: 'Hermès', size: 'One Size', fit: 'Unbekannt', price: '95.00',
    notes: 'Edles Detail fuer schlichte Outfits.',
    wornCount: 1, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
  },
  {
    id: 'demo-tasche',
    category: 'tasche',
    subtype: 'Ledertasche Schwarz',
    image: '/seed/tasche.svg',
    colorHex: '#1c1c1c', colorLabel: 'Schwarz', colorFamily: 'schwarz', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer', 'herbst', 'winter'], material: 'Leder',
    brand: 'A.P.C.', size: 'One Size', fit: 'Unbekannt', price: '210.00',
    notes: 'Taeglicher Begleiter fuer Buero und Freizeit.',
    wornCount: 25, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 150,
  },
  {
    id: 'demo-sonstiges',
    category: 'sonstiges',
    subtype: 'Wollmütze',
    image: '/seed/sonstiges.svg',
    colorHex: '#3f6b4a', colorLabel: 'Gruen', colorFamily: 'gruen', colorHue: 140, isNeutral: false,
    pattern: 'uni', season: ['winter'], material: 'Wolle',
    brand: 'Arket', size: 'One Size', fit: 'Unbekannt', price: '24.90',
    notes: 'Haelt im Winter warm, dezente Farbe.',
    wornCount: 5, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
];

export async function loadDemoItems(db) {
  for (const item of DEMO_ITEMS) {
    await db.addItem({ ...item });
  }
  return DEMO_ITEMS.length;
}
