// Beispiel-Kleidungsstuecke - 5 vollstaendig ausgefuellte Demo-Teile pro Kategorie,
// inklusive eigener Illustration unter /public/seed. Feste IDs, damit erneutes Laden
// die gleichen 45 Teile aktualisiert statt zu duplizieren.

export const DEMO_ITEMS = [
  // ---------- Oberteil ----------
  {
    id: 'demo-oberteil',
    category: 'oberteil',
    subtype: 'Oversized Pullover',
    image: '/seed/oberteil.svg',
    colorHex: '#8e8e8e', colorLabel: 'Grau', colorFamily: 'grau', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['herbst', 'winter'], material: 'Wolle-Mix',
    brand: 'COS', size: 'M', fit: 'Oversized', price: '69.00',
    notes: 'Sehr weich, gut zum Kombinieren mit Jeans.',
    wornCount: 4, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  },
  {
    id: 'demo-oberteil-2',
    category: 'oberteil',
    subtype: 'Basic T-Shirt Navy',
    image: '/seed/oberteil-2.svg',
    colorHex: '#24304f', colorLabel: 'Navy', colorFamily: 'navy', colorHue: 220, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer'], material: 'Baumwolle',
    brand: 'Uniqlo', size: 'M', fit: 'Regular', price: '14.90',
    notes: 'Alltags-Basic, mehrfach vorhanden.',
    wornCount: 22, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 200,
  },
  {
    id: 'demo-oberteil-3',
    category: 'oberteil',
    subtype: 'Strickjacke Creme',
    image: '/seed/oberteil-3.svg',
    colorHex: '#e8dcc8', colorLabel: 'Beige', colorFamily: 'beige', colorHue: 35, isNeutral: true,
    pattern: 'uni', season: ['herbst', 'fruehling'], material: 'Baumwolle-Strick',
    brand: 'Arket', size: 'S', fit: 'Regular', price: '79.00',
    notes: 'Leicht, gut als Layering-Piece.',
    wornCount: 6, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 40,
  },
  {
    id: 'demo-oberteil-4',
    category: 'oberteil',
    subtype: 'Business Hemd Schwarz',
    image: '/seed/oberteil-4.svg',
    colorHex: '#2b2b2b', colorLabel: 'Schwarz', colorFamily: 'schwarz', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer', 'herbst', 'winter'], material: 'Baumwolle-Popeline',
    brand: 'Hugo Boss', size: 'M', fit: 'Slim', price: '99.00',
    notes: 'Fuer Meetings und formellere Anlaesse.',
    wornCount: 9, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 70,
  },
  {
    id: 'demo-oberteil-5',
    category: 'oberteil',
    subtype: 'Blusenshirt Rosa',
    image: '/seed/oberteil-5.svg',
    colorHex: '#d98ba5', colorLabel: 'Pink', colorFamily: 'pink', colorHue: 320, isNeutral: false,
    pattern: 'uni', season: ['fruehling', 'sommer'], material: 'Viskose',
    brand: 'Mango', size: 'S', fit: 'Weit', price: '34.90',
    notes: 'Leicht und fliessend, gut fuer warme Tage.',
    wornCount: 3, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
  },

  // ---------- Hose ----------
  {
    id: 'demo-hose',
    category: 'hose',
    subtype: 'Straight Fit Jeans',
    image: '/seed/hose.svg',
    colorHex: '#3b6ea5', colorLabel: 'Blau', colorFamily: 'blau', colorHue: 210, isNeutral: false,
    pattern: 'uni', season: ['fruehling', 'herbst', 'sommer', 'winter'], material: 'Baumwolle-Denim',
    brand: 'Levi\'s', size: '32/32', fit: 'Regular', price: '89.90',
    notes: 'Klassiker, passt zu fast allem.',
    wornCount: 12, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 90,
  },
  {
    id: 'demo-hose-2',
    category: 'hose',
    subtype: 'Skinny Jeans Schwarz',
    image: '/seed/hose-2.svg',
    colorHex: '#232323', colorLabel: 'Schwarz', colorFamily: 'schwarz', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'herbst', 'sommer', 'winter'], material: 'Baumwolle-Denim',
    brand: 'Zara', size: '30/32', fit: 'Slim', price: '45.90',
    notes: 'Vielseitig, auch abends kombinierbar.',
    wornCount: 15, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 100,
  },
  {
    id: 'demo-hose-3',
    category: 'hose',
    subtype: 'Chino Beige',
    image: '/seed/hose-3.svg',
    colorHex: '#c7b48a', colorLabel: 'Beige', colorFamily: 'beige', colorHue: 35, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer', 'herbst'], material: 'Baumwolle',
    brand: 'Dockers', size: '32/30', fit: 'Regular', price: '59.00',
    notes: 'Gut fuer Buero-Casual.',
    wornCount: 7, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 55,
  },
  {
    id: 'demo-hose-4',
    category: 'hose',
    subtype: 'Leinenhose Weiss',
    image: '/seed/hose-4.svg',
    colorHex: '#ede8dd', colorLabel: 'Weiss', colorFamily: 'weiss', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['sommer'], material: 'Leinen',
    brand: 'Massimo Dutti', size: 'M', fit: 'Weit', price: '69.90',
    notes: 'Luftig, perfekt fuer den Urlaub.',
    wornCount: 4, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 25,
  },
  {
    id: 'demo-hose-5',
    category: 'hose',
    subtype: 'Cargohose Khaki',
    image: '/seed/hose-5.svg',
    colorHex: '#6e7b5a', colorLabel: 'Gruen', colorFamily: 'gruen', colorHue: 100, isNeutral: false,
    pattern: 'uni', season: ['herbst', 'fruehling'], material: 'Baumwolle-Twill',
    brand: 'Carhartt', size: '32/32', fit: 'Weit', price: '75.00',
    notes: 'Praktisch mit vielen Taschen.',
    wornCount: 5, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 35,
  },

  // ---------- Rock ----------
  {
    id: 'demo-rock',
    category: 'rock',
    subtype: 'Plisseerock Midi',
    image: '/seed/rock.svg',
    colorHex: '#c9a876', colorLabel: 'Beige', colorFamily: 'beige', colorHue: 35, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer'], material: 'Polyester',
    brand: 'Zara', size: 'S', fit: 'Weit', price: '39.95',
    notes: 'Toll fuer den Buero-Look mit Bluse.',
    wornCount: 2, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
  },
  {
    id: 'demo-rock-2',
    category: 'rock',
    subtype: 'Lederrock Mini Schwarz',
    image: '/seed/rock-2.svg',
    colorHex: '#1e1e1e', colorLabel: 'Schwarz', colorFamily: 'schwarz', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['herbst', 'winter'], material: 'Kunstleder',
    brand: 'Zara', size: 'S', fit: 'Slim', price: '35.00',
    notes: 'Fuer Abende und Ausgehen.',
    wornCount: 3, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 42,
  },
  {
    id: 'demo-rock-3',
    category: 'rock',
    subtype: 'Jeansrock',
    image: '/seed/rock-3.svg',
    colorHex: '#4e79a8', colorLabel: 'Blau', colorFamily: 'blau', colorHue: 210, isNeutral: false,
    pattern: 'uni', season: ['fruehling', 'sommer'], material: 'Denim',
    brand: 'Levi\'s', size: 'M', fit: 'Regular', price: '44.90',
    notes: 'Laessiger Alltags-Look.',
    wornCount: 6, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 60,
  },
  {
    id: 'demo-rock-4',
    category: 'rock',
    subtype: 'A-Linien Rock Rosa',
    image: '/seed/rock-4.svg',
    colorHex: '#e3afc0', colorLabel: 'Pink', colorFamily: 'pink', colorHue: 320, isNeutral: false,
    pattern: 'uni', season: ['fruehling', 'sommer'], material: 'Baumwolle',
    brand: 'H&M', size: 'S', fit: 'Weit', price: '24.90',
    notes: 'Suess kombiniert mit weisser Bluse.',
    wornCount: 1, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
  },
  {
    id: 'demo-rock-5',
    category: 'rock',
    subtype: 'Karorock Braun',
    image: '/seed/rock-5.svg',
    colorHex: '#8a6e4b', colorLabel: 'Braun', colorFamily: 'braun', colorHue: 30, isNeutral: true,
    pattern: 'kariert', season: ['herbst', 'winter'], material: 'Wolle-Mix',
    brand: 'Massimo Dutti', size: 'M', fit: 'Regular', price: '49.00',
    notes: 'Herbstlicher Business-Casual-Look.',
    wornCount: 2, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 18,
  },

  // ---------- Kleid ----------
  {
    id: 'demo-kleid',
    category: 'kleid',
    subtype: 'Sommerkleid A-Linie',
    image: '/seed/kleid.svg',
    colorHex: '#b3402f', colorLabel: 'Rot', colorFamily: 'rot', colorHue: 10, isNeutral: false,
    pattern: 'uni', season: ['sommer'], material: 'Leinen-Mix',
    brand: 'Mango', size: 'M', fit: 'Tailliert', price: '54.90',
    notes: 'Perfekt fuer heisse Tage, luftig.',
    wornCount: 3, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 45,
  },
  {
    id: 'demo-kleid-2',
    category: 'kleid',
    subtype: 'Cocktailkleid Schwarz',
    image: '/seed/kleid-2.svg',
    colorHex: '#1a1a1a', colorLabel: 'Schwarz', colorFamily: 'schwarz', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer', 'herbst', 'winter'], material: 'Polyester-Mix',
    brand: 'Zara', size: 'M', fit: 'Tailliert', price: '49.90',
    notes: 'Kleines Schwarzes fuer jeden Anlass.',
    wornCount: 8, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 80,
  },
  {
    id: 'demo-kleid-3',
    category: 'kleid',
    subtype: 'Blumenkleid Midi',
    image: '/seed/kleid-3.svg',
    colorHex: '#e7b7c4', colorLabel: 'Pink', colorFamily: 'pink', colorHue: 320, isNeutral: false,
    pattern: 'geblumt', season: ['fruehling', 'sommer'], material: 'Viskose',
    brand: 'Mango', size: 'S', fit: 'Weit', price: '59.90',
    notes: 'Romantischer Look fuer Frühlingstage.',
    wornCount: 2, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
  },
  {
    id: 'demo-kleid-4',
    category: 'kleid',
    subtype: 'Etuikleid Navy',
    image: '/seed/kleid-4.svg',
    colorHex: '#24406b', colorLabel: 'Navy', colorFamily: 'navy', colorHue: 220, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'herbst'], material: 'Polyester-Mix',
    brand: 'Hugo Boss', size: 'M', fit: 'Tailliert', price: '119.00',
    notes: 'Fuer Buero und Geschaeftstermine.',
    wornCount: 5, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 65,
  },
  {
    id: 'demo-kleid-5',
    category: 'kleid',
    subtype: 'Maxikleid Gelb',
    image: '/seed/kleid-5.svg',
    colorHex: '#e7c24a', colorLabel: 'Gelb', colorFamily: 'gelb', colorHue: 55, isNeutral: false,
    pattern: 'uni', season: ['sommer'], material: 'Baumwolle',
    brand: 'Free People', size: 'M', fit: 'Weit', price: '89.00',
    notes: 'Auffaellige Sommerfarbe, toll im Urlaub.',
    wornCount: 1, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },

  // ---------- Jacke ----------
  {
    id: 'demo-jacke',
    category: 'jacke',
    subtype: 'Wollmantel Camel',
    image: '/seed/jacke.svg',
    colorHex: '#b08d5b', colorLabel: 'Braun', colorFamily: 'braun', colorHue: 35, isNeutral: true,
    pattern: 'uni', season: ['herbst', 'winter'], material: 'Wolle',
    brand: 'Massimo Dutti', size: 'M', fit: 'Regular', price: '189.00',
    notes: 'Investment-Piece, haelt sehr warm.',
    wornCount: 6, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 60,
  },
  {
    id: 'demo-jacke-2',
    category: 'jacke',
    subtype: 'Bikerjacke Leder',
    image: '/seed/jacke-2.svg',
    colorHex: '#1b1b1b', colorLabel: 'Schwarz', colorFamily: 'schwarz', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'herbst'], material: 'Leder',
    brand: 'AllSaints', size: 'M', fit: 'Slim', price: '349.00',
    notes: 'Lässiger Kontrast zu femininen Outfits.',
    wornCount: 9, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 110,
  },
  {
    id: 'demo-jacke-3',
    category: 'jacke',
    subtype: 'Jeansjacke',
    image: '/seed/jacke-3.svg',
    colorHex: '#4e79a8', colorLabel: 'Blau', colorFamily: 'blau', colorHue: 210, isNeutral: false,
    pattern: 'uni', season: ['fruehling', 'sommer', 'herbst'], material: 'Denim',
    brand: 'Levi\'s', size: 'M', fit: 'Regular', price: '79.90',
    notes: 'Vielseitiger Klassiker als Übergangsjacke.',
    wornCount: 11, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 95,
  },
  {
    id: 'demo-jacke-4',
    category: 'jacke',
    subtype: 'Parka Oliv',
    image: '/seed/jacke-4.svg',
    colorHex: '#5c6b4f', colorLabel: 'Gruen', colorFamily: 'gruen', colorHue: 100, isNeutral: false,
    pattern: 'uni', season: ['herbst', 'winter'], material: 'Baumwolle-Nylon',
    brand: 'Carhartt', size: 'L', fit: 'Weit', price: '159.00',
    notes: 'Warm und wasserabweisend.',
    wornCount: 7, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 75,
  },
  {
    id: 'demo-jacke-5',
    category: 'jacke',
    subtype: 'Blazer Navy',
    image: '/seed/jacke-5.svg',
    colorHex: '#24304f', colorLabel: 'Navy', colorFamily: 'navy', colorHue: 220, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer', 'herbst'], material: 'Wolle-Mix',
    brand: 'Hugo Boss', size: 'M', fit: 'Tailliert', price: '229.00',
    notes: 'Fuer Buero und formelle Anlaesse.',
    wornCount: 10, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 85,
  },

  // ---------- Schuhe ----------
  {
    id: 'demo-schuhe',
    category: 'schuhe',
    subtype: 'Leder-Sneaker Weiss',
    image: '/seed/schuhe.svg',
    colorHex: '#f2f2ee', colorLabel: 'Weiss', colorFamily: 'weiss', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer', 'herbst'], material: 'Leder',
    brand: 'Common Projects', size: '42', fit: 'Regular', price: '149.00',
    notes: 'Neutraler Allrounder-Schuh.',
    wornCount: 18, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 120,
  },
  {
    id: 'demo-schuhe-2',
    category: 'schuhe',
    subtype: 'Sneaker Schwarz',
    image: '/seed/schuhe-2.svg',
    colorHex: '#2b2b2b', colorLabel: 'Schwarz', colorFamily: 'schwarz', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer', 'herbst', 'winter'], material: 'Leder',
    brand: 'Adidas', size: '42', fit: 'Regular', price: '99.00',
    notes: 'Passt zu fast jedem Outfit.',
    wornCount: 20, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 130,
  },
  {
    id: 'demo-schuhe-3',
    category: 'schuhe',
    subtype: 'Sneaker Rot',
    image: '/seed/schuhe-3.svg',
    colorHex: '#a6362e', colorLabel: 'Rot', colorFamily: 'rot', colorHue: 0, isNeutral: false,
    pattern: 'uni', season: ['fruehling', 'sommer'], material: 'Textil-Mix',
    brand: 'Nike', size: '42', fit: 'Regular', price: '89.00',
    notes: 'Farbtupfer fuer schlichte Outfits.',
    wornCount: 4, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 22,
  },
  {
    id: 'demo-schuhe-4',
    category: 'schuhe',
    subtype: 'Loafer Braun',
    image: '/seed/schuhe-4.svg',
    colorHex: '#6b4a2e', colorLabel: 'Braun', colorFamily: 'braun', colorHue: 30, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'herbst'], material: 'Leder',
    brand: 'Church\'s', size: '43', fit: 'Regular', price: '259.00',
    notes: 'Elegant fuer Buero-Looks.',
    wornCount: 6, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 50,
  },
  {
    id: 'demo-schuhe-5',
    category: 'schuhe',
    subtype: 'Sneaker Beige',
    image: '/seed/schuhe-5.svg',
    colorHex: '#d8c3a5', colorLabel: 'Beige', colorFamily: 'beige', colorHue: 35, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer', 'herbst'], material: 'Wildleder',
    brand: 'Veja', size: '41', fit: 'Regular', price: '119.00',
    notes: 'Dezent und vielseitig.',
    wornCount: 10, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 68,
  },

  // ---------- Accessoire ----------
  {
    id: 'demo-accessoire',
    category: 'accessoire',
    subtype: 'Seidenschal',
    image: '/seed/accessoire.svg',
    colorHex: '#6b3f5c', colorLabel: 'Lila', colorFamily: 'lila', colorHue: 300, isNeutral: false,
    pattern: 'uni', season: ['herbst', 'winter', 'fruehling'], material: 'Seide',
    brand: 'Hermès', size: 'One Size', fit: 'Unbekannt', price: '95.00',
    notes: 'Edles Detail fuer schlichte Outfits.',
    wornCount: 1, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
  },
  {
    id: 'demo-accessoire-2',
    category: 'accessoire',
    subtype: 'Wollschal Schwarz',
    image: '/seed/accessoire-2.svg',
    colorHex: '#1e1e1e', colorLabel: 'Schwarz', colorFamily: 'schwarz', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['winter', 'herbst'], material: 'Wolle',
    brand: 'Arket', size: 'One Size', fit: 'Unbekannt', price: '39.00',
    notes: 'Warm und dezent kombinierbar.',
    wornCount: 8, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 55,
  },
  {
    id: 'demo-accessoire-3',
    category: 'accessoire',
    subtype: 'Seidenschal Rot',
    image: '/seed/accessoire-3.svg',
    colorHex: '#a6362e', colorLabel: 'Rot', colorFamily: 'rot', colorHue: 0, isNeutral: false,
    pattern: 'uni', season: ['herbst', 'winter'], material: 'Seide',
    brand: 'Zara', size: 'One Size', fit: 'Unbekannt', price: '19.90',
    notes: 'Farblicher Akzent zu neutralen Outfits.',
    wornCount: 2, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
  },
  {
    id: 'demo-accessoire-4',
    category: 'accessoire',
    subtype: 'Schal Senfgelb',
    image: '/seed/accessoire-4.svg',
    colorHex: '#c9a227', colorLabel: 'Gelb', colorFamily: 'gelb', colorHue: 55, isNeutral: false,
    pattern: 'uni', season: ['herbst'], material: 'Baumwolle-Mix',
    brand: 'H&M', size: 'One Size', fit: 'Unbekannt', price: '14.90',
    notes: 'Warmer Farbakzent im Herbst.',
    wornCount: 3, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 28,
  },
  {
    id: 'demo-accessoire-5',
    category: 'accessoire',
    subtype: 'Streifenschal',
    image: '/seed/accessoire-5.svg',
    colorHex: '#3c5a78', colorLabel: 'Blau', colorFamily: 'blau', colorHue: 210, isNeutral: false,
    pattern: 'gestreift', season: ['fruehling', 'herbst'], material: 'Baumwolle',
    brand: 'Uniqlo', size: 'One Size', fit: 'Unbekannt', price: '12.90',
    notes: 'Legerer Streifen-Look.',
    wornCount: 5, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 33,
  },

  // ---------- Tasche ----------
  {
    id: 'demo-tasche',
    category: 'tasche',
    subtype: 'Ledertasche Schwarz',
    image: '/seed/tasche.svg',
    colorHex: '#1c1c1c', colorLabel: 'Schwarz', colorFamily: 'schwarz', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer', 'herbst', 'winter'], material: 'Leder',
    brand: 'A.P.C.', size: 'One Size', fit: 'Unbekannt', price: '210.00',
    notes: 'Taeglicher Begleiter fuer Buero und Freizeit.',
    wornCount: 25, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 150,
  },
  {
    id: 'demo-tasche-2',
    category: 'tasche',
    subtype: 'Ledertasche Braun',
    image: '/seed/tasche-2.svg',
    colorHex: '#6b4a2e', colorLabel: 'Braun', colorFamily: 'braun', colorHue: 30, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'herbst'], material: 'Leder',
    brand: 'Madewell', size: 'One Size', fit: 'Unbekannt', price: '178.00',
    notes: 'Warmer Farbton, passt zu Camel und Beige.',
    wornCount: 9, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 62,
  },
  {
    id: 'demo-tasche-3',
    category: 'tasche',
    subtype: 'Handtasche Rot',
    image: '/seed/tasche-3.svg',
    colorHex: '#a6362e', colorLabel: 'Rot', colorFamily: 'rot', colorHue: 0, isNeutral: false,
    pattern: 'uni', season: ['fruehling', 'sommer', 'herbst', 'winter'], material: 'Kunstleder',
    brand: 'Zara', size: 'One Size', fit: 'Unbekannt', price: '45.90',
    notes: 'Auffaelliges Statement-Piece.',
    wornCount: 4, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 19,
  },
  {
    id: 'demo-tasche-4',
    category: 'tasche',
    subtype: 'Shopper Beige',
    image: '/seed/tasche-4.svg',
    colorHex: '#d8c3a5', colorLabel: 'Beige', colorFamily: 'beige', colorHue: 35, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'sommer'], material: 'Canvas',
    brand: 'Arket', size: 'One Size', fit: 'Unbekannt', price: '55.00',
    notes: 'Grosser Alltags-Shopper.',
    wornCount: 14, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 88,
  },
  {
    id: 'demo-tasche-5',
    category: 'tasche',
    subtype: 'Umhaengetasche Navy',
    image: '/seed/tasche-5.svg',
    colorHex: '#24406b', colorLabel: 'Navy', colorFamily: 'navy', colorHue: 220, isNeutral: true,
    pattern: 'uni', season: ['fruehling', 'herbst', 'winter'], material: 'Leder',
    brand: 'Fossil', size: 'One Size', fit: 'Unbekannt', price: '129.00',
    notes: 'Kompakt fuer den Alltag.',
    wornCount: 7, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 48,
  },

  // ---------- Sonstiges ----------
  {
    id: 'demo-sonstiges',
    category: 'sonstiges',
    subtype: 'Wollmütze',
    image: '/seed/sonstiges.svg',
    colorHex: '#3f6b4a', colorLabel: 'Gruen', colorFamily: 'gruen', colorHue: 140, isNeutral: false,
    pattern: 'uni', season: ['winter'], material: 'Wolle',
    brand: 'Arket', size: 'One Size', fit: 'Unbekannt', price: '24.90',
    notes: 'Haelt im Winter warm, dezente Farbe.',
    wornCount: 5, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    id: 'demo-sonstiges-2',
    category: 'sonstiges',
    subtype: 'Beanie Schwarz',
    image: '/seed/sonstiges-2.svg',
    colorHex: '#1e1e1e', colorLabel: 'Schwarz', colorFamily: 'schwarz', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['winter', 'herbst'], material: 'Wolle-Mix',
    brand: 'Carhartt', size: 'One Size', fit: 'Unbekannt', price: '22.00',
    notes: 'Passt zu jedem Wintermantel.',
    wornCount: 12, isFavorite: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 72,
  },
  {
    id: 'demo-sonstiges-3',
    category: 'sonstiges',
    subtype: 'Beanie Grau',
    image: '/seed/sonstiges-3.svg',
    colorHex: '#7a7a7a', colorLabel: 'Grau', colorFamily: 'grau', colorHue: 0, isNeutral: true,
    pattern: 'uni', season: ['winter'], material: 'Wolle',
    brand: 'H&M', size: 'One Size', fit: 'Unbekannt', price: '9.90',
    notes: 'Schlichtes Zweitmodell.',
    wornCount: 3, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 26,
  },
  {
    id: 'demo-sonstiges-4',
    category: 'sonstiges',
    subtype: 'Beanie Rot',
    image: '/seed/sonstiges-4.svg',
    colorHex: '#a6362e', colorLabel: 'Rot', colorFamily: 'rot', colorHue: 0, isNeutral: false,
    pattern: 'uni', season: ['winter'], material: 'Wolle',
    brand: 'Arket', size: 'One Size', fit: 'Unbekannt', price: '24.90',
    notes: 'Farbtupfer im grauen Winteralltag.',
    wornCount: 2, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 9,
  },
  {
    id: 'demo-sonstiges-5',
    category: 'sonstiges',
    subtype: 'Beanie Senfgelb',
    image: '/seed/sonstiges-5.svg',
    colorHex: '#c9a227', colorLabel: 'Gelb', colorFamily: 'gelb', colorHue: 55, isNeutral: false,
    pattern: 'uni', season: ['winter', 'herbst'], material: 'Wolle-Mix',
    brand: 'Monki', size: 'One Size', fit: 'Unbekannt', price: '17.90',
    notes: 'Warmer Farbakzent zu neutralen Mänteln.',
    wornCount: 1, isFavorite: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
];

export async function loadDemoItems(db) {
  for (const item of DEMO_ITEMS) {
    await db.addItem({ ...item });
  }
  return DEMO_ITEMS.length;
}
